# fly.toml app configuration file generated for metabreaker-live on 2026-05-23T21:20:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'metabreaker-live'
primary_region = 'lax'

[mounts]
  source = "request_cache"
  destination = "/work/cache"

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
